---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    web_server: nginx
    servername: sentry.devmeter 192.168.100.100
    timezone: Europe/Brussels
  vars_files:
    - vars/pgsql.yml
    - vars/sentry.yml
    - vars/supervisor.yml
    - vars/common.yml
    - vars/nginx.yml
  roles:
    - init
    - nginx
    - pgsql
    - sentry
    - supervisor
    - app
